name: todo_console
description: Aplicación de consola en Dart para la gestión de una lista de tareas (To-Do List).
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
